name: linux-archive-backend-dev

services:
  fastapi:
    build:
      context: ../../ # <- Esto apunta a la raÃ­z del repo
      dockerfile: docker/dev/Dockerfile
    env_file:
      - ../../.env
    ports:
      - "${DOCKER_DEV_FASTAPI_PORT}:8000"
    volumes:
      - ../../:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: no
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  postgres_db:
    image: postgres:18-alpine
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DOCKER_DEV_POSTGRES_DB_NAME}
      - POSTGRES_USER=${DOCKER_DEV_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${DOCKER_DEV_POSTGRES_DB_PASSWORD}
      - TZ=America/Mexico_City
    ports:
      - "${DOCKER_DEV_POSTGRES_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_db_data:
